{
  "comments": [
    {
      "unresolved": false,
      "key": {
        "uuid": "3bf599b9_d69bc446",
        "filename": "/PATCHSET_LEVEL",
        "patchSetId": 1
      },
      "lineNbr": 0,
      "author": {
        "id": 1293738
      },
      "writtenOn": "2021-06-14T16:44:50Z",
      "side": 1,
      "message": "Does this bug affect the old version of virtio_gpu in 5.4 and earlier?",
      "revId": "5f2c65e6d65d77b3fafbec4887a142e2279014be",
      "serverId": "85c56323-6fa9-3386-8a01-6480fb634889"
    },
    {
      "unresolved": false,
      "key": {
        "uuid": "2ecae088_aae73f70",
        "filename": "/PATCHSET_LEVEL",
        "patchSetId": 1
      },
      "lineNbr": 0,
      "author": {
        "id": 1561731
      },
      "writtenOn": "2021-06-14T16:52:25Z",
      "side": 1,
      "message": "I don\u0027t believe so. In 5.4, the virtio_gpu_cmd_context_create() calls happens immediately in virtio_gpu_driver_open(). See https://android.googlesource.com/kernel/common-modules/virtual-device/+/refs/heads/android12-5.4/virtio_gpu/virtgpu_kms.c#282 virtio_gpu_driver_open() -\u003e virtio_gpu_context_create() -\u003e virtio_gpu_cmd_context_create().",
      "parentUuid": "3bf599b9_d69bc446",
      "revId": "5f2c65e6d65d77b3fafbec4887a142e2279014be",
      "serverId": "85c56323-6fa9-3386-8a01-6480fb634889"
    }
  ]
}